// Auto-generated favorites list
// Multi-user support - each user has their own favorites
// Updated: 2026-02-25 22:48:30 UTC

export const favorites = {
  "816774921": ["love-story-indila", "fnaf-song-1", "sad-song-we-the-kings", "fallen-down", "rush-e", "blue", "its-been-so-long", "pork-soda", "creep", "gravity-falls-main-title-theme"],
  "451609118": ["love-story-indila"],
  "36619352": ["erika"],
  "742785636": ["pork-soda", "all-i-want-for-christmas-is-you"],
  "43305368": ["all-girls-are-the-same", "stick-season", "pork-soda", "promise", "love-story-indila", "chest-pain-i-love", "if-you-love-these-people", "debito-di-sonno", "five-nights-at-freddys-movie", "his-theme"],
  "79251703": ["another-love", "izmir-marsi"],
  "698251037": ["unravel"],
  "836959497": ["kid-cudi", "his-theme"],
  "938081548": ["interstellar", "aria-math"],
  "733578271": ["grandmas-home"],
  "156008784": ["song-of-storms", "grandmas-home", "eternal-dream-murder-drones", "creep", "tough-luck", "new-computers"],
  "198019641": ["robbery-juice-wrld"],
  "112398055": ["chest-pain-i-love"],
  "639401484": ["super-mario-bros-theme", "orcalero-orcala-funk", "moonlight-on-the-river", "old-doll", "dearly-beloved", "back-to-friends", "love-wave-to-earth", "strangers", "touch-tone-telephone"],
  "457769316": ["five-nights-at-freddys-movie", "i-wanna-be-yours"],
  "891179348": [],
  "858946055": ["pork-soda"],
  "848879732": ["carol-of-the-bells", "from-the-start", "the-world-death-note-op", "if-i-am-with-you", "the-cruel-angels-thesis", "kawaikute-gomen", "nope-your-too-late-i-already-died", "poster-boy"],
  "943232059": ["promise"],
  "636831239": ["minecraft-sweden", "runaway", "door", "rush-e", "mice-on-venus"],
  "234341824": ["monsoon", "took-her-to-the-o", "nope-your-too-late-i-already-died"],
  "343855507": ["my-ordinary-life", "hotline-bling", "let-her-go", "sailor-song", "turning-page", "undressed"],
  "3422383": [],
  "589229028": ["robbery-juice-wrld"],
  "140584214": ["stick-season", "debito-di-sonno", "cigarettes-out-the-window"],
  "333436434": ["end-of-beginning", "mia-and-sebastians-theme"],
  "516882949": ["anata-no-koibito-ni-naritai", "passionfruit", "interstellar"],
  "350463994": ["rush-e", "thick-of-it"],
  "295939480": ["see-you-again-tyler-the-creator", "join-me-in-death", "burn", "stay-rihanna", "fur-elise", "resonanse-heavens-secret-requiem", "kid-cudi", "all-girls-are-the-same", "the-way-things-go", "symphony", "red-swan", "rick-roll", "over", "karma-police", "oops-did-it-again", "see-you-again-charlie-puth", "all-star", "symphony-no-5", "super-mario-bros-theme", "the-box", "interstellar", "thick-of-it", "duvet", "the-star-spangled-banner", "hotline-bling", "silhouette", "unravel", "halloween-theme-michael-myers", "best-friend", "nyan-cat", "raining-tacos", "beastars-wolf-and-rabbit", "moonlight-sonata-1st-movement", "moonlight-sonata-3rd-movement", "sweater-weather", "my-ordinary-life", "in-the-pool", "piano-man", "dark-red", "washing-machine-heart", "white-ferrari", "zeldas-lullaby", "upside-down", "boys-don-t-cry", "melancholy", "commatose-glass-beach", "girl-song", "we-are-charlie-kirk", "runaway-aurora", "once-upon-a-time", "you-are-not-suguru-geto", "still-dre", "mr-sandman", "shinunoga-e-wa"],
  "88508638": [],
  "859330476": ["buddy-holly-weezer", "end-of-beginning", "until-i-found-you", "the-fate-of-ophelia"],
  "531819202": ["new-computers"],
  "135767004": [],
  "415988107": [],
  "67973817": ["squid-game"],
  "820831933": ["cardigan"],
  "686585648": ["pork-soda"],
  "280133457": ["golden-hour", "order-heaven-pierce-her", "interstellar", "the-lost-soul-down", "passionfruit", "if-i-am-with-you", "clair-de-lune", "resonanse-heavens-secret-requiem", "never-meant-to-belong", "rush-e", "lost-woods", "requiem-for-the-lost-ones"]
};
